apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
spec:
  secretTargetRef:
    - parameter: connection
      name: app-secrets
      key: azure-storage-connection-string
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaler
spec:
  scaleTargetRef:
    name: consumer
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: azure-queue
      metadata:
        queueName: {{ .Values.queueName }}
        queueLength: "3"
        accountName: devstoreaccount1
        cloud: Private
        endpointSuffix: "http://azurite:10001/devstoreaccount1"
      authenticationRef:
        name: azure-queue-auth