apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  azure-storage-connection-string: {{ .Values.azureStorageConnectionString }}
  postgresql-connection-string: {{ .Values.postgresqlConnectionString }}